# Exercise One

Requirements:
1. Implement this algorithm in Python. Use the NumPy ndarray object for your matrices;
2. Give the asymptotic time complexity of the above algorithm or your implementation (they should be the same). Justify and explain your answer.

Suggestions:
1. Implement the algorithm with nested lists and compare the algorithms on different sizes of matrices;
2. Compare with built-in multiplication functions;
3. Look at multiplying more than two matrices, or at other operations on matrices.

In [1]:
import numpy as np
import time

# Algorithm 1: Square-Matrix-Multiply using NumPy
def SMM_np(A, B):
    n = A.shape[0]  # number of rows of A
    C = np.zeros((n, n))  # initialize new n x n matrix C
    
    for i in range(n):
        for j in range(n):
            for k in range(n):
                C[i, j] += A[i, k] * B[k, j]  # compute the dot product
    
    return C

# Algorithm 2: Square-Matrix-Multiply using nested lists
def SMM_lists(A, B):
    n = len(A)  # number of rows of A
    C = [[0]*n for _ in range(n)]  # initialize new n x n matrix C
    
    for i in range(n):
        for j in range(n):
            for k in range(n):
                C[i][j] += A[i][k] * B[k][j]  # compute the dot product
    
    return C

# Compare algorithms on different sizes of matrices
sizes = [10, 100, 500]  # Example sizes of matrices
for size in sizes:
    A_np = np.random.rand(size, size)
    B_np = np.random.rand(size, size)
    A_list = [[np.random.rand() for _ in range(size)] for _ in range(size)]
    B_list = [[np.random.rand() for _ in range(size)] for _ in range(size)]

    # Time the NumPy implementation
    start_np = time.time()
    result_np = SMM_np(A_np, B_np)
    end_np = time.time()
    np_time = end_np - start_np

    # Time the nested lists implementation
    start_lists = time.time()
    result_lists = SMM_lists(A_list, B_list)
    end_lists = time.time()
    lists_time = end_lists - start_lists

    print(f"Matrix size: {size}x{size}")
    print(f"NumPy implementation time: {np_time} seconds")
    print(f"Nested lists implementation time: {lists_time} seconds")

# Compare with built-in multiplication functions
start_builtin = time.time()
result_builtin = np.matmul(A_np, B_np)
end_builtin = time.time()
builtin_time = end_builtin - start_builtin
print(f"Built-in multiplication time: {builtin_time} seconds")

Matrix size: 10x10
NumPy implementation time: 0.0 seconds
Nested lists implementation time: 0.0 seconds
Matrix size: 100x100
NumPy implementation time: 0.2861495018005371 seconds
Nested lists implementation time: 0.06073737144470215 seconds
Matrix size: 500x500
NumPy implementation time: 77.07705211639404 seconds
Nested lists implementation time: 23.80222511291504 seconds
Built-in multiplication time: 0.18256640434265137 seconds


In [2]:
# Function to transpose a matrix using NumPy
def transpose_matrix_np(A):
    return np.transpose(A)

# Function to find eigenvalues of a matrix using NumPy
def find_eigenvalues_np(A):
    return np.linalg.eigvals(A)

# Example usage of the functions
# Transpose a matrix
A_transpose = transpose_matrix_np(A_np)
print("Transposed matrix:")
print(A_transpose)

# Find eigenvalues of a matrix
eigenvalues = find_eigenvalues_np(A_np)
print("Eigenvalues of the matrix:")
print(eigenvalues)

Transposed matrix:
[[0.15074054 0.1511098  0.81942923 ... 0.22222279 0.49014737 0.93994555]
 [0.34799879 0.7672143  0.03022011 ... 0.05980828 0.42880213 0.21944949]
 [0.18528011 0.13604624 0.26015033 ... 0.9435989  0.86944855 0.05901871]
 ...
 [0.21923528 0.89175553 0.19493726 ... 0.82838203 0.09459485 0.41926677]
 [0.18897361 0.46577537 0.78514768 ... 0.03446973 0.75093294 0.79304603]
 [0.06791962 0.27146727 0.80416233 ... 0.49802102 0.08003806 0.64192922]]
Eigenvalues of the matrix:
[ 2.50301077e+02+0.j          6.55793487e+00+0.36208072j
  6.55793487e+00-0.36208072j  4.64712009e+00+4.83722599j
  4.64712009e+00-4.83722599j  5.95018758e+00+2.1709605j
  5.95018758e+00-2.1709605j   2.78634889e+00+5.96688959j
  2.78634889e+00-5.96688959j  5.26777334e+00+3.39279951j
  5.26777334e+00-3.39279951j  4.88687981e+00+3.91616808j
  4.88687981e+00-3.91616808j  3.51990557e+00+5.30064491j
  3.51990557e+00-5.30064491j  1.93805965e+00+6.1302037j
  1.93805965e+00-6.1302037j   2.13574462e+00+5.96604182j

# Exercise Two

Requirements:
1. Describe and explain the algorithm. It should contain at least the following:
    - recursiveness: How is it recursive? What is (the criteria for) the base case? How does the recursion step reduce to the base case?
    - divide-and-conquer : How does this algorithm fit into the divide-andconquer approach? Explain each step of divide, conquer, and combine for this algorithm (as in slide 8 / pdf page 16 of the lecture slides).
2. Implement the recursive algorithm in Python. Reflect on which steps of the pseudocode were straightforward to implement and which hid a lot of complexity behind their language.
3. Do a complexity analysis for the SMMRec algorithm. First comment on the complexity of the base case, divide step, conquer step, and combine step separately, then put it all together.
    - Use slides 20-21 of the lecture slides (pages 40-45 of the pdf) of Complexity lecture 2 as a guideline.
    - You do not have to do the tree analysis (slides 22-23), but do take a guess what the final complexity is.
    
Suggestions:
1. Do a tree analysis;
2. Test and compare the practical speed with the non-recursive algorithm

In [3]:
def SMMRec(A, B):
    """
    Recursive algorithm for square matrix multiplication
    
    Parameters:
        A (list of lists): Matrix A
        B (list of lists): Matrix B
    
    Returns:
        C (list of lists): Resultant matrix C = A * B
    """
    n = len(A)
    C = [[0 for _ in range(n)] for _ in range(n)]
    
    # Base case: if the size is 1, compute the multiplication directly
    if n == 1:
        C[0][0] = A[0][0] * B[0][0]
    else:
        # Divide: Quarter matrices A, B, and C
        A11, A12, A21, A22 = quarter_matrix(A)
        B11, B12, B21, B22 = quarter_matrix(B)
        
        # Conquer: Recursively compute submatrices
        # Each recursive call represents a node in the recursion tree
        C11 = SMMRec(A11, B11)  # Node 1
        C12 = SMMRec(A11, B12)  # Node 2
        C21 = SMMRec(A21, B11)  # Node 3
        C22 = SMMRec(A21, B12)  # Node 4
        
        # Combine: Combine results
        combine_matrix(C, C11, C12, C21, C22)
    
    return C

def quarter_matrix(M):
    """
    Divide matrix M into four equal-sized submatrices
    
    Parameters:
        M (list of lists): Input matrix
    
    Returns:
        A11, A12, A21, A22 (list of lists): Four submatrices of M
    """
    n = len(M)
    mid = n // 2
    return M[:mid], M[:mid], M[mid:], M[mid:]

def combine_matrix(C, C11, C12, C21, C22):
    """
    Combine four submatrices into matrix C
    
    Parameters:
        C (list of lists): Resultant matrix C
        C11, C12, C21, C22 (list of lists): Four submatrices
    """
    n = len(C)
    mid = n // 2
    for i in range(mid):
        for j in range(mid):
            C[i][j] = C11[i][j]
            C[i][j+mid] = C12[i][j]
            C[i+mid][j] = C21[i][j]
            C[i+mid][j+mid] = C22[i][j]

# Test the algorithm
A = [[6, 3, 10, 4],
     [10, 3, 6, 10],
     [6, 9, 2, 5],
     [4, 2, 9, 4]]
B = [[6, 7, 2, 9],
     [8, 5, 4, 3],
     [3, 6, 8, 1],
     [7, 4, 2, 5]]

# Perform matrix multiplication using the recursive algorithm
result = SMMRec(A, B)

# Print the result
for row in result:
    print(row)

[36, 36, 36, 36]
[60, 60, 60, 60]
[36, 36, 36, 36]
[24, 24, 24, 24]


# Exercise Three

Requirements:
1. Reflect on the difference between (complexity of) addition/subtraction and multiplication on matrices.
2. Do a complexity analysis of the Strassen algorithm.
   - Instead of starting from scratch, you can also take your result from Exercise 2 and adapt to the optimisation; explain what changes in the complexity formula with these optimisations.
   
Suggestions:
1. Implement and test the algorithm;
2. Discuss other optimisations;

In [4]:
def SMMStrassen(A, B):
    """
    Strassen algorithm for square matrix multiplication
    
    Parameters:
        A (list of lists): Matrix A
        B (list of lists): Matrix B
    
    Returns:
        C (list of lists): Resultant matrix C = A * B
    """
    n = len(A)
    # Base case: if the size is 1, compute the multiplication directly
    if n == 1:
        return [[A[0][0] * B[0][0]]]
    else:
        # Divide: Quarter matrices A, B, and C
        A11, A12, A21, A22 = quarter_matrix(A)
        B11, B12, B21, B22 = quarter_matrix(B)
        
        # Compute the 7 auxiliary matrices
        P1 = SMMStrassen(A11, subtract_matrix(B12, B22))
        P2 = SMMStrassen(add_matrix(A11, A12), B22)
        P3 = SMMStrassen(add_matrix(A21, A22), B11)
        P4 = SMMStrassen(A22, subtract_matrix(B21, B11))
        P5 = SMMStrassen(add_matrix(A11, A22), add_matrix(B11, B22))
        P6 = SMMStrassen(subtract_matrix(A12, A22), add_matrix(B21, B22))
        P7 = SMMStrassen(subtract_matrix(A11, A21), add_matrix(B11, B12))
        
        # Combine: Combine results
        C11 = add_matrix(subtract_matrix(add_matrix(P5, P4), P2), P6)
        C12 = add_matrix(P1, P2)
        C21 = add_matrix(P3, P4)
        C22 = subtract_matrix(subtract_matrix(add_matrix(P5, P1), P3), P7)
        
        # Combine the quarters into the result matrix
        C = combine_matrix(C11, C12, C21, C22)
    
    return C

def add_matrix(A, B):
    """Add two matrices element-wise"""
    n = len(A)
    return [[A[i][j] + B[i][j] for j in range(n)] for i in range(n)]

def subtract_matrix(A, B):
    """Subtract matrix B from matrix A element-wise"""
    n = len(A)
    return [[A[i][j] - B[i][j] for j in range(n)] for i in range(n)]

def quarter_matrix(M):
    """
    Divide matrix M into four equal-sized submatrices
    
    Parameters:
        M (list of lists): Input matrix
    
    Returns:
        A11, A12, A21, A22 (list of lists): Four submatrices of M
    """
    n = len(M)
    mid = n // 2
    return [row[:mid] for row in M[:mid]], [row[mid:] for row in M[:mid]], \
           [row[:mid] for row in M[mid:]], [row[mid:] for row in M[mid:]]

def combine_matrix(C11, C12, C21, C22):
    """
    Combine four submatrices into one matrix
    
    Parameters:
        C11, C12, C21, C22 (list of lists): Four submatrices
    
    Returns:
        C (list of lists): Combined matrix
    """
    n = len(C11)
    result = [[0] * (2 * n) for _ in range(2 * n)]
    for i in range(n):
        for j in range(n):
            result[i][j] = C11[i][j]
            result[i][j + n] = C12[i][j]
            result[i + n][j] = C21[i][j]
            result[i + n][j + n] = C22[i][j]
    return result

# Test the Strassen algorithm
A = [[6, 3, 10, 4],
     [10, 3, 6, 10],
     [6, 9, 2, 5],
     [4, 2, 9, 4]]
B = [[6, 7, 2, 9],
     [8, 5, 4, 3],
     [3, 6, 8, 1],
     [7, 4, 2, 5]]

# Perform matrix multiplication using the Strassen algorithm
result = SMMStrassen(A, B)

# Print the result
for row in result:
    print(row)

[118, 133, 112, 93]
[172, 161, 100, 155]
[149, 119, 74, 108]
[95, 108, 96, 71]


In [8]:
def Strassen(A, B):
    n = len(A)
    C = [[0 for _ in range(n)] for _ in range(n)]

    if n == 1:
        C[0][0] = A[0][0] * B[0][0]
    else:
        # Divide: Quarter matrices A, B, and C
        A11, A12, A21, A22 = quarter_matrix(A)
        B11, B12, B21, B22 = quarter_matrix(B)

        # Calculate Strassen parameters
        S1 = subtract_matrices(B12, B22)
        S2 = add_matrices(A11, A12)
        S3 = add_matrices(A21, A22)
        S4 = subtract_matrices(B21, B11)
        S5 = add_matrices(A11, A22)
        S6 = add_matrices(B11, B22)
        S7 = subtract_matrices(A12, A22)
        S8 = add_matrices(B21, B22)
        S9 = subtract_matrices(A11, A21)
        S10 = add_matrices(B11, B12)

        # Recursive calls
        P1 = Strassen(A11, S1)
        P2 = Strassen(S2, B22)
        P3 = Strassen(S3, B11)
        P4 = Strassen(A22, S4)
        P5 = Strassen(S5, S6)
        P6 = Strassen(S7, S8)
        P7 = Strassen(S9, S10)

        # Combine results
        C11 = add_matrices(subtract_matrices(add_matrices(P5, P4), P2), P6)
        C12 = add_matrices(P1, P2)
        C21 = add_matrices(P3, P4)
        C22 = subtract_matrices(subtract_matrices(add_matrices(P5, P1), P3), P7)

        # Construct resultant matrix C
        combine_matrix(C, C11, C12, C21, C22)

    return C

def quarter_matrix1(M):
    n = len(M)
    mid = n // 2
    return [row[:mid] for row in M[:mid]], [row[mid:] for row in M[:mid]], [row[:mid] for row in M[mid:]], [row[mid:] for row in M[mid:]]

def add_matrices1(A, B):
    return [[A[i][j] + B[i][j] for j in range(len(A))] for i in range(len(A))]

def subtract_matrices1(A, B):
    return [[A[i][j] - B[i][j] for j in range(len(A))] for i in range(len(A))]

def combine_matrix1(C, C11, C12, C21, C22):
    n = len(C)
    mid = n // 2
    for i in range(mid):
        for j in range(mid):
            C[i][j] = C11[i][j]
            C[i][j+mid] = C12[i][j]
            C[i+mid][j] = C21[i][j]
            C[i+mid][j+mid] = C22[i][j]

# Test the algorithm
A = [[6, 3, 10, 4],
     [10, 3, 6, 10],
     [6, 9, 2, 5],
     [4, 2, 9, 4]]
B = [[6, 7, 2, 9],
     [8, 5, 4, 3],
     [3, 6, 8, 1],
     [7, 4, 2, 5]]

# Perform matrix multiplication using the Strassen algorithm
result = Strassen(A, B)

# Print the result
for row in result:
    print(row)

[118, 133, 112, 93]
[172, 161, 100, 155]
[149, 119, 74, 108]
[95, 108, 96, 71]


In [9]:
def add_matrices2(matrix1, matrix2):
    # Helper function to add two matrices
    return [[matrix1[i][j] + matrix2[i][j] for j in range(len(matrix1))] for i in range(len(matrix1))]

def subtract_matrices2(matrix1, matrix2):
    # Helper function to subtract one matrix from another
    return [[matrix1[i][j] - matrix2[i][j] for j in range(len(matrix1))] for i in range(len(matrix1))]

def strassen2(matrix1, matrix2):
    n = len(matrix1)
    
    # Base case: When matrices are 1x1
    if n == 1:
        return [[matrix1[0][0] * matrix2[0][0]]]
    
    # Divide matrices into quarters
    a11 = [row[:n//2] for row in matrix1[:n//2]]
    a12 = [row[n//2:] for row in matrix1[:n//2]]
    a21 = [row[:n//2] for row in matrix1[n//2:]]
    a22 = [row[n//2:] for row in matrix1[n//2:]]
    
    b11 = [row[:n//2] for row in matrix2[:n//2]]
    b12 = [row[n//2:] for row in matrix2[:n//2]]
    b21 = [row[:n//2] for row in matrix2[n//2:]]
    b22 = [row[n//2:] for row in matrix2[n//2:]]
    
    # Calculate S matrices
    s1 = subtract_matrices(b12, b22)
    s2 = add_matrices(a11, a12)
    s3 = add_matrices(a21, a22)
    s4 = subtract_matrices(b21, b11)
    s5 = add_matrices(a11, a22)
    s6 = add_matrices(b11, b22)
    s7 = subtract_matrices(a12, a22)
    s8 = add_matrices(b21, b22)
    s9 = subtract_matrices(a11, a21)
    s10 = add_matrices(b11, b12)
    
    # Calculate P matrices
    p1 = strassen(a11, s1)
    p2 = strassen(s2, b22)
    p3 = strassen(s3, b11)
    p4 = strassen(a22, s4)
    p5 = strassen(s5, s6)
    p6 = strassen(s7, s8)
    p7 = strassen(s9, s10)
    
    # Calculate result matrices
    c11 = add_matrices(subtract_matrices(add_matrices(p5, p4), p2), p6)
    c12 = add_matrices(p1, p2)
    c21 = add_matrices(p3, p4)
    c22 = subtract_matrices(subtract_matrices(add_matrices(p5, p1), p3), p7)
    
    # Combine result matrices
    result = [[0] * n for _ in range(n)]
    for i in range(n//2):
        for j in range(n//2):
            result[i][j] = c11[i][j]
            result[i][j + n//2] = c12[i][j]
            result[i + n//2][j] = c21[i][j]
            result[i + n//2][j + n//2] = c22[i][j]
    
    return result

# Example usage:
matrix1 = [[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]]
matrix2 = [[17, 18, 19, 20], [21, 22, 23, 24], [25, 26, 27, 28], [29, 30, 31, 32]]
result = strassen(matrix1, matrix2)
for row in result:
    print(row)


[250, 260, 270, 280]
[618, 644, 670, 696]
[986, 1028, 1070, 1112]
[1354, 1412, 1470, 1528]
